### ISSUE TITLE
How to detect verified captcha on template file?

### ISSUE THREAD

**Issue by azrachaman** [KnugiHK/flask-hcaptcha#12] opened 2024-06-19 12:16 UTC
I need to check if the captcha is verified or not and enable/disable the submit button. Is this currently possible?

**Comment by KnugiHK** [comment] 2024-06-19 14:12
Yes. You can use the `data-callback` or `callback` configuration. Learn more on https://docs.hcaptcha.com/configuration#hcaptcha-container-configuration.

**Comment by azrachaman** [comment] 2024-06-20 06:27
Got it. Thanks @KnugiHK.

**Comment by dannypernik** [comment] 2024-11-05 17:11
@KnugiHK apologies for my ignorance, but I'm struggling with adding data-callback to {{ hcaptcha }} in my jinja variable. Or do I need to set it elsewhere?

**Comment by KnugiHK** [comment] 2024-11-12 15:52
> @KnugiHK apologies for my ignorance, but I'm struggling with adding data-callback to {{ hcaptcha }} in my jinja variable. Or do I need to set it elsewhere?

Hi! In the current release, `{{ hcaptcha }}` does not support the any custom data attribute. However, I've just added support for optional data attributes in commit 0957eef. To use this feature, pass the attribute without the `data-` prefix when initializing the plugin. For example:

```python
hcaptcha = hCaptcha(app, callback="done") # Where done is a JS function.
```

This will result in:

```html
<div class="h-captcha" data-sitekey="20000000-ffff-ffff-ffff-000000000002" data-theme="light" data-callback="done">
```

You can try this in `dev` branch.

**Comment by KnugiHK** [comment] 2024-11-12 15:53
```python
from flask import Flask, render_template_string, request
from flask_hcaptcha import hCaptcha

app = Flask(__name__)

# Replace these with your actual hCaptcha site key and secret key
app.config['HCAPTCHA_SITE_KEY'] = '20000000-ffff-ffff-ffff-000000000002'
app.config['HCAPTCHA_SECRET_KEY'] = '0x0000000000000000000000000000000000000000'

# Initialize hCaptcha
hcaptcha = hCaptcha(app, callback="done1")

# Simple in-memory form submission storage (for demonstration)
submissions = []

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        # Verify hCaptcha
        if not hcaptcha.verify():
            return render_template_string(HTML_FORM, error="hCaptcha verification failed. Please try again.")
        
        # If hCaptcha verification is successful, process form data
        name = request.form['name']
        submissions.append({'name': name})
        return render_template_string(HTML_FORM, success="Form submitted successfully!", submissions=submissions)

    return render_template_string(HTML_FORM)

# Simple HTML form with hCaptcha widget
HTML_FORM = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask hCaptcha Example</title>
</head>
<body>
    <h1>Submit Your Information</h1>

    {% if error %}
    <div style="color: red;">{{ error }}</div>
    {% endif %}
    {% if success %}
    <div style="color: green;">{{ success }}</div>
    {% endif %}
    <script>
        function done1(){console.log("done1")}
        function done2(){console.log("done2")}
    </script>

    <form method="POST">
        <label for="name">Name:</label><br>
        <input type="text" id="name" name="name" required><br><br>
        {{ hcaptcha }}  <!-- hCaptcha widget -->
        {{ hcaptcha_with(callback='done2') }}  <!-- hCaptcha widget -->

        <br><br>
        <button type="submit">Submit</button>
    </form>

    <h2>Submissions</h2>
    <ul>
    {% for submission in submissions %}
        <li>{{ submission.name }} - {{ submission.email }}</li>
    {% endfor %}
    </ul>
</body>
</html>
'''

if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by dannypernik** [comment] 2024-11-13 01:02
Yes, amazing thank you!!

**Comment by dannypernik** [comment] 2024-11-13 02:33
To clarify, can multiple data attributes be set in this way for the same hcaptcha?

**Comment by KnugiHK** [comment] 2024-11-13 14:20
> To clarify, can multiple data attributes be set in this way for the same hcaptcha?

Yes. For example if you want `data-size="normal"`:

```py
hcaptcha = hCaptcha(app, callback="done", size="normal")
```

Although I haven't test it, it should work. If not, let me know!

**Comment by dannypernik** [comment] 2024-11-16 03:24
@KnugiHK confirmed it works to set `data-callback` and `data-size` together! It's interesting to set these attributes on initialization because it means all hcaptchas on my site need to have the same configuration. It's not a problem for me, but there's only one page for which I need `data-callback` and the rest log `[hCaptcha] Callback 'captchaPassed' is not defined` to the console. I realize it's a simple fix, just an observation.

**Comment by KnugiHK** [comment] 2024-11-17 10:18
> @KnugiHK confirmed it works to set `data-callback` and `data-size` together! It's interesting to set these attributes on initialization because it means all hcaptchas on my site need to have the same configuration. It's not a problem for me, but there's only one page for which I need `data-callback` and the rest log `[hCaptcha] Callback 'captchaPassed' is not defined` to the console. I realize it's a simple fix, just an observation.

Good observation! I added another function for that: `hcaptcha_with`. See my updated example above.

**Comment by dannypernik** [comment] 2024-11-17 22:02
Awesome! So can `{{ hcaptcha_with(callback="done2" }}` be used if the `callback` parameter is not set on initialization? Is it safe to assume `{{ hcaptcha }}` does not need to be included alongside `hcaptcha_with` as in the example above?

**Comment by KnugiHK** [comment] 2024-11-18 08:19
> Awesome! So can `{{ hcaptcha_with(callback="done2" }}` be used if the `callback` parameter is not set on initialization? Is it safe to assume `{{ hcaptcha }}` does not need to be included alongside `hcaptcha_with` as in the example above?

Yes. You can use either `{{ hcaptcha_with() }}` or `{{ hcaptcha }}` to set a default widget.

`{{ hcaptcha_with() }}` and `{{ hcaptcha }}` do not depend on each other. The example is just to show there are two possible ways to do so now.

**Comment by dannypernik** [comment] 2024-11-18 21:15
That’s perfect. Thank you for supporting these use cases!

**Comment by KnugiHK** [comment] 2024-11-19 11:38
Released in 0.7.0.

**Closed as completed by KnugiHK** 2024-11-19 11:38 UTC
Labels: enhancement

**Comment by dannypernik** [comment] 2024-11-21 03:52
Curious about how releases work. Your Readme and pip indicate the latest version is 0.6.0, but I see that the latest download available is 0.7.0. Is there a review process or some other reason for the difference?

**Comment by KnugiHK** [comment] 2024-11-24 09:40
Yeah... The PyPi release failed, and I haven't had the time to address it yet...

**Comment by dannypernik** [comment] 2024-11-26 04:45
Got it, all good!
